from globais import load_imagem

cafe_img = load_imagem('cafe.png')
background_img = load_imagem('Cenário.jpeg')
cracha_img = load_imagem('cracha.png')
piso_img = load_imagem('piso.png')
livro_img = load_imagem('livros.png')
moeda_img = load_imagem('moedas.png')
jogador_img = load_imagem('personagem_andar_1.png')
catraca_img = load_imagem('catraca.png')
porta_img = load_imagem('porta.png')
robo_cin_img = load_imagem('robo_cin.png')
janela_img = load_imagem('janela.png')
jeep_img = load_imagem('jeep.png')
agua_img = load_imagem('agua_junta.png')
tela_menu = load_imagem('tela_menu.png')
tela_instrucoes = load_imagem('tela_instrucoes.png')
tela_creditos = load_imagem('tela_creditos.png')
tela_perdeu = load_imagem('tela_perdeu.png')
tela_ganhou = load_imagem('tela_venceu.png')
botao_img = load_imagem('botao.png')
nome_jogo = load_imagem('NomeJogo.png')
bebedouro_img = load_imagem('bebedouro.png')
placa_img = load_imagem('placa.png')
